<?php

$jogadores = [

    // ==================== PREMIER LEAGUE ====================

    // Arsenal
    ["nome" => "David Raya", "posicao" => "GOL"],
    ["nome" => "William Saliba", "posicao" => "ZAG"],
    ["nome" => "Gabriel Magalhães", "posicao" => "ZAG"],
    ["nome" => "Cristhian Mosquera", "posicao" => "ZAG"],
    ["nome" => "Jurriën Timber", "posicao" => "LD"],
    ["nome" => "Ben White", "posicao" => "LD"],
    ["nome" => "Riccardo Calafiori", "posicao" => "LE"],
    ["nome" => "Myles Lewis-Skelly", "posicao" => "LE"],
    ["nome" => "Oleksandr Zinchenko", "posicao" => "LE"],
    ["nome" => "Declan Rice", "posicao" => "VOL"],
    ["nome" => "Martín Zubimendi", "posicao" => "VOL"],
    ["nome" => "Mikel Merino", "posicao" => "MC"],
    ["nome" => "Martin Ødegaard", "posicao" => "MEI"],
    ["nome" => "Eberechi Eze", "posicao" => "MEI"],
    ["nome" => "Ethan Nwaneri", "posicao" => "MEI"],
    ["nome" => "Bukayo Saka", "posicao" => "PD"],
    ["nome" => "Noni Madueke", "posicao" => "PD"],
    ["nome" => "Gabriel Martinelli", "posicao" => "PE"],
    ["nome" => "Leandro Trossard", "posicao" => "PE"],
    ["nome" => "Kai Havertz", "posicao" => "ATA"],
    ["nome" => "Gabriel Jesus", "posicao" => "ATA"],
    ["nome" => "Viktor Gyökeres", "posicao" => "ATA"],

    // Manchester City
    ["nome" => "Gianluigi Donnarumma", "posicao" => "GOL"],
    ["nome" => "Rúben Dias", "posicao" => "ZAG"],
    ["nome" => "Joško Gvardiol", "posicao" => "ZAG"],
    ["nome" => "Manuel Akanji", "posicao" => "ZAG"],
    ["nome" => "John Stones", "posicao" => "ZAG"],
    ["nome" => "Nathan Aké", "posicao" => "ZAG"],
    ["nome" => "Abdukodir Khusanov", "posicao" => "ZAG"],
    ["nome" => "Vitor Reis", "posicao" => "ZAG"],
    ["nome" => "Rayan Aït-Nouri", "posicao" => "LE"],
    ["nome" => "Nico O'Reilly", "posicao" => "LE"],
    ["nome" => "Rico Lewis", "posicao" => "LD"],
    ["nome" => "Rodri", "posicao" => "VOL"],
    ["nome" => "Nico González", "posicao" => "VOL"],
    ["nome" => "Mateo Kovačić", "posicao" => "MC"],
    ["nome" => "Matheus Nunes", "posicao" => "MC"],
    ["nome" => "Bernardo Silva", "posicao" => "MC"],
    ["nome" => "Tijjani Reijnders", "posicao" => "MC"],
    ["nome" => "Phil Foden", "posicao" => "MEI"],
    ["nome" => "Rayan Cherki", "posicao" => "MEI"],
    ["nome" => "Claudio Echeverri", "posicao" => "MEI"],
    ["nome" => "Jérémy Doku", "posicao" => "PE"],
    ["nome" => "Jack Grealish", "posicao" => "PE"],
    ["nome" => "Savinho", "posicao" => "PD"],
    ["nome" => "Oscar Bobb", "posicao" => "PD"],
    ["nome" => "Erling Haaland", "posicao" => "ATA"],
    ["nome" => "Omar Marmoush", "posicao" => "ATA"],

    // Liverpool
    ["nome" => "Alisson", "posicao" => "GOL"],
    ["nome" => "Giorgi Mamardashvili", "posicao" => "GOL"],
    ["nome" => "Virgil van Dijk", "posicao" => "ZAG"],
    ["nome" => "Ibrahima Konaté", "posicao" => "ZAG"],
    ["nome" => "Joe Gomez", "posicao" => "ZAG"],
    ["nome" => "Conor Bradley", "posicao" => "LD"],
    ["nome" => "Jeremie Frimpong", "posicao" => "LD"],
    ["nome" => "Andrew Robertson", "posicao" => "LE"],
    ["nome" => "Milos Kerkez", "posicao" => "LE"],
    ["nome" => "Ryan Gravenberch", "posicao" => "VOL"],
    ["nome" => "Wataru Endo", "posicao" => "VOL"],
    ["nome" => "Alexis Mac Allister", "posicao" => "MC"],
    ["nome" => "Dominik Szoboszlai", "posicao" => "MC"],
    ["nome" => "Curtis Jones", "posicao" => "MC"],
    ["nome" => "Florian Wirtz", "posicao" => "MEI"],
    ["nome" => "Harvey Elliott", "posicao" => "MEI"],
    ["nome" => "Mohamed Salah", "posicao" => "PD"],
    ["nome" => "Cody Gakpo", "posicao" => "PE"],
    ["nome" => "Federico Chiesa", "posicao" => "PE"],
    ["nome" => "Rio Ngumoha", "posicao" => "PE"],
    ["nome" => "Hugo Ekitiké", "posicao" => "ATA"],
    ["nome" => "Alexander Isak", "posicao" => "ATA"],

    // Chelsea
    ["nome" => "Robert Sánchez", "posicao" => "GOL"],
    ["nome" => "Filip Jörgensen", "posicao" => "GOL"],
    ["nome" => "Levi Colwill", "posicao" => "ZAG"],
    ["nome" => "Wesley Fofana", "posicao" => "ZAG"],
    ["nome" => "Trevoh Chalobah", "posicao" => "ZAG"],
    ["nome" => "Benoît Badiashile", "posicao" => "ZAG"],
    ["nome" => "Tosin Adarabioyo", "posicao" => "ZAG"],
    ["nome" => "Jorrel Hato", "posicao" => "ZAG"],
    ["nome" => "Reece James", "posicao" => "LD"],
    ["nome" => "Malo Gusto", "posicao" => "LD"],
    ["nome" => "Marc Cucurella", "posicao" => "LE"],
    ["nome" => "Moisés Caicedo", "posicao" => "VOL"],
    ["nome" => "Romeo Lavia", "posicao" => "VOL"],
    ["nome" => "Andrey Santos", "posicao" => "VOL"],
    ["nome" => "Enzo Fernández", "posicao" => "MC"],
    ["nome" => "Cole Palmer", "posicao" => "MEI"],
    ["nome" => "Pedro Neto", "posicao" => "PD"],
    ["nome" => "Estêvão", "posicao" => "PD"],
    ["nome" => "Jamie Gittens", "posicao" => "PE"],
    ["nome" => "Alejandro Garnacho", "posicao" => "PE"],
    ["nome" => "João Pedro", "posicao" => "ATA"],
    ["nome" => "Nicolas Jackson", "posicao" => "ATA"],
    ["nome" => "Liam Delap", "posicao" => "ATA"],

    // Manchester United
    ["nome" => "André Onana", "posicao" => "GOL"],
    ["nome" => "Altay Bayındır", "posicao" => "GOL"],
    ["nome" => "Senne Lammens", "posicao" => "GOL"],
    ["nome" => "Lisandro Martínez", "posicao" => "ZAG"],
    ["nome" => "Matthijs de Ligt", "posicao" => "ZAG"],
    ["nome" => "Leny Yoro", "posicao" => "ZAG"],
    ["nome" => "Harry Maguire", "posicao" => "ZAG"],
    ["nome" => "Noussair Mazraoui", "posicao" => "LD"],
    ["nome" => "Diogo Dalot", "posicao" => "LD"],
    ["nome" => "Luke Shaw", "posicao" => "LE"],
    ["nome" => "Patrick Dorgu", "posicao" => "LE"],
    ["nome" => "Casemiro", "posicao" => "VOL"],
    ["nome" => "Manuel Ugarte", "posicao" => "VOL"],
    ["nome" => "Kobbie Mainoo", "posicao" => "MC"],
    ["nome" => "Bruno Fernandes", "posicao" => "MEI"],
    ["nome" => "Mason Mount", "posicao" => "MEI"],
    ["nome" => "Bryan Mbeumo", "posicao" => "PD"],
    ["nome" => "Amad Diallo", "posicao" => "PD"],
    ["nome" => "Matheus Cunha", "posicao" => "ATA"],
    ["nome" => "Benjamin Šeško", "posicao" => "ATA"],
    ["nome" => "Joshua Zirkzee", "posicao" => "ATA"],

    // Tottenham
    ["nome" => "Guglielmo Vicario", "posicao" => "GOL"],
    ["nome" => "Micky van de Ven", "posicao" => "ZAG"],
    ["nome" => "Cristian Romero", "posicao" => "ZAG"],
    ["nome" => "Radu Drăguşin", "posicao" => "ZAG"],
    ["nome" => "Kevin Danso", "posicao" => "ZAG"],
    ["nome" => "Luka Vušković", "posicao" => "ZAG"],
    ["nome" => "Pedro Porro", "posicao" => "LD"],
    ["nome" => "Djed Spence", "posicao" => "LD"],
    ["nome" => "Destiny Udogie", "posicao" => "LE"],
    ["nome" => "João Palhinha", "posicao" => "VOL"],
    ["nome" => "Yves Bissouma", "posicao" => "VOL"],
    ["nome" => "Rodrigo Bentancur", "posicao" => "MC"],
    ["nome" => "Pape Matar Sarr", "posicao" => "MC"],
    ["nome" => "Lucas Bergvall", "posicao" => "MC"],
    ["nome" => "Archie Gray", "posicao" => "MC"],
    ["nome" => "James Maddison", "posicao" => "MEI"],
    ["nome" => "Xavi Simons", "posicao" => "MEI"],
    ["nome" => "Mohammed Kudus", "posicao" => "PD"],
    ["nome" => "Dejan Kulusevski", "posicao" => "PD"],
    ["nome" => "Brennan Johnson", "posicao" => "PD"],
    ["nome" => "Wilson Odobert", "posicao" => "PE"],
    ["nome" => "Richarlison", "posicao" => "ATA"],
    ["nome" => "Dominic Solanke", "posicao" => "ATA"],
    ["nome" => "Mathys Tel", "posicao" => "ATA"],
    ["nome" => "Randal Kolo Muani", "posicao" => "ATA"],

    // Newcastle
    ["nome" => "Nick Pope", "posicao" => "GOL"],
    ["nome" => "Sven Botman", "posicao" => "ZAG"],
    ["nome" => "Fabian Schär", "posicao" => "ZAG"],
    ["nome" => "Dan Burn", "posicao" => "ZAG"],
    ["nome" => "Malick Thiaw", "posicao" => "ZAG"],
    ["nome" => "Tino Livramento", "posicao" => "LD"],
    ["nome" => "Kieran Trippier", "posicao" => "LD"],
    ["nome" => "Lewis Hall", "posicao" => "LE"],
    ["nome" => "Bruno Guimarães", "posicao" => "MC"],
    ["nome" => "Sandro Tonali", "posicao" => "MC"],
    ["nome" => "Joelinton", "posicao" => "MC"],
    ["nome" => "Joe Willock", "posicao" => "MC"],
    ["nome" => "Jacob Ramsey", "posicao" => "MC"],
    ["nome" => "Anthony Gordon", "posicao" => "PE"],
    ["nome" => "Harvey Barnes", "posicao" => "PE"],
    ["nome" => "Anthony Elanga", "posicao" => "PD"],
    ["nome" => "Jacob Murphy", "posicao" => "PD"],
    ["nome" => "Nick Woltemade", "posicao" => "ATA"],
    ["nome" => "Yoane Wissa", "posicao" => "ATA"],

    // Aston Villa
    ["nome" => "Emiliano Martínez", "posicao" => "GOL"],
    ["nome" => "Ezri Konsa", "posicao" => "ZAG"],
    ["nome" => "Pau Torres", "posicao" => "ZAG"],
    ["nome" => "Tyrone Mings", "posicao" => "ZAG"],
    ["nome" => "Victor Lindelöf", "posicao" => "ZAG"],
    ["nome" => "Matty Cash", "posicao" => "LD"],
    ["nome" => "Lucas Digne", "posicao" => "LE"],
    ["nome" => "Ian Maatsen", "posicao" => "LE"],
    ["nome" => "Boubacar Kamara", "posicao" => "VOL"],
    ["nome" => "Amadou Onana", "posicao" => "VOL"],
    ["nome" => "Youri Tielemans", "posicao" => "MC"],
    ["nome" => "John McGinn", "posicao" => "MC"],
    ["nome" => "Morgan Rogers", "posicao" => "MEI"],
    ["nome" => "Emiliano Buendía", "posicao" => "MEI"],
    ["nome" => "Leon Bailey", "posicao" => "PD"],
    ["nome" => "Jadon Sancho", "posicao" => "PE"],
    ["nome" => "Ollie Watkins", "posicao" => "ATA"],
    ["nome" => "Donyell Malen", "posicao" => "ATA"],
    ["nome" => "Evann Guessand", "posicao" => "ATA"],

    // Brighton
    ["nome" => "Bart Verbruggen", "posicao" => "GOL"],
    ["nome" => "Jan Paul van Hecke", "posicao" => "ZAG"],
    ["nome" => "Lewis Dunk", "posicao" => "ZAG"],
    ["nome" => "Adam Webster", "posicao" => "ZAG"],
    ["nome" => "Ferdi Kadıoğlu", "posicao" => "LE"],
    ["nome" => "Pervis Estupiñán", "posicao" => "LE"],
    ["nome" => "Joël Veltman", "posicao" => "LD"],
    ["nome" => "Mats Wieffer", "posicao" => "VOL"],
    ["nome" => "Carlos Baleba", "posicao" => "VOL"],
    ["nome" => "Yasin Ayari", "posicao" => "MC"],
    ["nome" => "Matt O'Riley", "posicao" => "MC"],
    ["nome" => "Diego Gómez", "posicao" => "MC"],
    ["nome" => "Jack Hinshelwood", "posicao" => "MC"],
    ["nome" => "Georginio Rutter", "posicao" => "MEI"],
    ["nome" => "Brajan Gruda", "posicao" => "MEI"],
    ["nome" => "Kaoru Mitoma", "posicao" => "PE"],
    ["nome" => "Yankuba Minteh", "posicao" => "PD"],
    ["nome" => "Danny Welbeck", "posicao" => "ATA"],

    // Crystal Palace
    ["nome" => "Dean Henderson", "posicao" => "GOL"],
    ["nome" => "Marc Guéhi", "posicao" => "ZAG"],
    ["nome" => "Maxence Lacroix", "posicao" => "ZAG"],
    ["nome" => "Chris Richards", "posicao" => "ZAG"],
    ["nome" => "Daniel Muñoz", "posicao" => "LD"],
    ["nome" => "Tyrick Mitchell", "posicao" => "LE"],
    ["nome" => "Adam Wharton", "posicao" => "MC"],
    ["nome" => "Jefferson Lerma", "posicao" => "VOL"],
    ["nome" => "Daichi Kamada", "posicao" => "MC"],
    ["nome" => "Ismaïla Sarr", "posicao" => "PD"],
    ["nome" => "Jean-Philippe Mateta", "posicao" => "ATA"],
    ["nome" => "Eddie Nketiah", "posicao" => "ATA"],

    // West Ham
    ["nome" => "Alphonse Areola", "posicao" => "GOL"],
    ["nome" => "Max Kilman", "posicao" => "ZAG"],
    ["nome" => "Jean-Clair Todibo", "posicao" => "ZAG"],
    ["nome" => "Aaron Wan-Bissaka", "posicao" => "LD"],
    ["nome" => "El Hadji Malick Diouf", "posicao" => "LE"],
    ["nome" => "Tomáš Souček", "posicao" => "VOL"],
    ["nome" => "Edson Álvarez", "posicao" => "VOL"],
    ["nome" => "Guido Rodríguez", "posicao" => "VOL"],
    ["nome" => "Mateus Fernandes", "posicao" => "MC"],
    ["nome" => "Lucas Paquetá", "posicao" => "MEI"],
    ["nome" => "Jarrod Bowen", "posicao" => "PD"],
    ["nome" => "Crysencio Summerville", "posicao" => "PE"],
    ["nome" => "Niclas Füllkrug", "posicao" => "ATA"],
    ["nome" => "Callum Wilson", "posicao" => "ATA"],

    // Everton
    ["nome" => "Jordan Pickford", "posicao" => "GOL"],
    ["nome" => "Jarrad Branthwaite", "posicao" => "ZAG"],
    ["nome" => "James Tarkowski", "posicao" => "ZAG"],
    ["nome" => "Jake O'Brien", "posicao" => "ZAG"],
    ["nome" => "Vitaliy Mykolenko", "posicao" => "LE"],
    ["nome" => "Idrissa Gueye", "posicao" => "VOL"],
    ["nome" => "Tim Iroegbunam", "posicao" => "VOL"],
    ["nome" => "James Garner", "posicao" => "MC"],
    ["nome" => "Kiernan Dewsbury-Hall", "posicao" => "MC"],
    ["nome" => "Abdoulaye Doucouré", "posicao" => "MC"],
    ["nome" => "Iliman Ndiaye", "posicao" => "PE"],
    ["nome" => "Dwight McNeil", "posicao" => "PE"],
    ["nome" => "Beto", "posicao" => "ATA"],
    ["nome" => "Thierno Barry", "posicao" => "ATA"],

    // Brentford
    ["nome" => "Caoimhín Kelleher", "posicao" => "GOL"],
    ["nome" => "Nathan Collins", "posicao" => "ZAG"],
    ["nome" => "Sepp van den Berg", "posicao" => "ZAG"],
    ["nome" => "Kristoffer Ajer", "posicao" => "ZAG"],
    ["nome" => "Rico Henry", "posicao" => "LE"],
    ["nome" => "Aaron Hickey", "posicao" => "LD"],
    ["nome" => "Christian Nørgaard", "posicao" => "VOL"],
    ["nome" => "Mathias Jensen", "posicao" => "MC"],
    ["nome" => "Vitaly Janelt", "posicao" => "MC"],
    ["nome" => "Jordan Henderson", "posicao" => "MC"],
    ["nome" => "Mikkel Damsgaard", "posicao" => "MEI"],
    ["nome" => "Keane Lewis-Potter", "posicao" => "PE"],
    ["nome" => "Kevin Schade", "posicao" => "PE"],
    ["nome" => "Dango Ouattara", "posicao" => "PD"],
    ["nome" => "Igor Thiago", "posicao" => "ATA"],

    // Fulham
    ["nome" => "Bernd Leno", "posicao" => "GOL"],
    ["nome" => "Joachim Andersen", "posicao" => "ZAG"],
    ["nome" => "Calvin Bassey", "posicao" => "ZAG"],
    ["nome" => "Kenny Tete", "posicao" => "LD"],
    ["nome" => "Timothy Castagne", "posicao" => "LD"],
    ["nome" => "Antonee Robinson", "posicao" => "LE"],
    ["nome" => "Sander Berge", "posicao" => "VOL"],
    ["nome" => "Sasa Lukić", "posicao" => "MC"],
    ["nome" => "Alex Iwobi", "posicao" => "MC"],
    ["nome" => "Andreas Pereira", "posicao" => "MEI"],
    ["nome" => "Emile Smith Rowe", "posicao" => "MEI"],
    ["nome" => "Harry Wilson", "posicao" => "PD"],
    ["nome" => "Samuel Chukwueze", "posicao" => "PD"],
    ["nome" => "Adama Traoré", "posicao" => "PD"],
    ["nome" => "Raúl Jiménez", "posicao" => "ATA"],
    ["nome" => "Rodrigo Muniz", "posicao" => "ATA"],

    // Wolverhampton
    ["nome" => "José Sá", "posicao" => "GOL"],
    ["nome" => "Sam Johnstone", "posicao" => "GOL"],
    ["nome" => "Emmanuel Agbadou", "posicao" => "ZAG"],
    ["nome" => "Santiago Bueno", "posicao" => "ZAG"],
    ["nome" => "Matt Doherty", "posicao" => "LD"],
    ["nome" => "João Gomes", "posicao" => "VOL"],
    ["nome" => "André", "posicao" => "VOL"],
    ["nome" => "Jean-Ricner Bellegarde", "posicao" => "MC"],
    ["nome" => "Rodrigo Gomes", "posicao" => "PD"],
    ["nome" => "Jhon Arias", "posicao" => "PD"],
    ["nome" => "Hwang Hee-chan", "posicao" => "PE"],
    ["nome" => "Jørgen Strand Larsen", "posicao" => "ATA"],
    ["nome" => "Tolu Arokodare", "posicao" => "ATA"],

    // Bournemouth
    ["nome" => "Djordje Petrović", "posicao" => "GOL"],
    ["nome" => "Bafodé Diakité", "posicao" => "ZAG"],
    ["nome" => "Adrien Truffert", "posicao" => "LE"],
    ["nome" => "Álex Jiménez", "posicao" => "LD"],
    ["nome" => "Tyler Adams", "posicao" => "VOL"],
    ["nome" => "Alex Scott", "posicao" => "MC"],
    ["nome" => "Ryan Christie", "posicao" => "MEI"],
    ["nome" => "Justin Kluivert", "posicao" => "MEI"],
    ["nome" => "Antoine Semenyo", "posicao" => "PE"],
    ["nome" => "Amine Adli", "posicao" => "PE"],
    ["nome" => "Marcus Tavernier", "posicao" => "PD"],
    ["nome" => "David Brooks", "posicao" => "PD"],
    ["nome" => "Evanilson", "posicao" => "ATA"],
    ["nome" => "Enes Ünal", "posicao" => "ATA"],

    // Nottingham Forest
    ["nome" => "Matz Sels", "posicao" => "GOL"],
    ["nome" => "Murillo", "posicao" => "ZAG"],
    ["nome" => "Nikola Milenković", "posicao" => "ZAG"],
    ["nome" => "Morato", "posicao" => "ZAG"],
    ["nome" => "Ola Aina", "posicao" => "LD"],
    ["nome" => "Neco Williams", "posicao" => "LD"],
    ["nome" => "Ibrahim Sangaré", "posicao" => "VOL"],
    ["nome" => "Nicolás Domínguez", "posicao" => "MC"],
    ["nome" => "Elliot Anderson", "posicao" => "MC"],
    ["nome" => "Morgan Gibbs-White", "posicao" => "MEI"],
    ["nome" => "Callum Hudson-Odoi", "posicao" => "PE"],
    ["nome" => "Omari Hutchinson", "posicao" => "PD"],
    ["nome" => "Dan Ndoye", "posicao" => "PD"],
    ["nome" => "Chris Wood", "posicao" => "ATA"],
    ["nome" => "Taiwo Awoniyi", "posicao" => "ATA"],
    ["nome" => "Igor Jesus", "posicao" => "ATA"],

    // Leeds United
    ["nome" => "Joe Rodon", "posicao" => "ZAG"],
    ["nome" => "Pascal Struijk", "posicao" => "ZAG"],
    ["nome" => "Ethan Ampadu", "posicao" => "VOL"],
    ["nome" => "Anton Stach", "posicao" => "MC"],
    ["nome" => "Ao Tanaka", "posicao" => "MC"],
    ["nome" => "Sean Longstaff", "posicao" => "MC"],
    ["nome" => "Brenden Aaronson", "posicao" => "MEI"],
    ["nome" => "Daniel James", "posicao" => "PD"],
    ["nome" => "Noah Okafor", "posicao" => "PE"],
    ["nome" => "Wilfried Gnonto", "posicao" => "PE"],
    ["nome" => "Dominic Calvert-Lewin", "posicao" => "ATA"],
    ["nome" => "Lukas Nmecha", "posicao" => "ATA"],

    // Sunderland
    ["nome" => "Robin Roefs", "posicao" => "GOL"],
    ["nome" => "Omar Alderete", "posicao" => "ZAG"],
    ["nome" => "Reinildo", "posicao" => "LE"],
    ["nome" => "Granit Xhaka", "posicao" => "MC"],
    ["nome" => "Habib Diarra", "posicao" => "MC"],
    ["nome" => "Noah Sadiki", "posicao" => "VOL"],
    ["nome" => "Enzo Le Fée", "posicao" => "MEI"],
    ["nome" => "Chemsdine Talbi", "posicao" => "PE"],
    ["nome" => "Simon Adingra", "posicao" => "PE"],
    ["nome" => "Bertrand Traoré", "posicao" => "PD"],
    ["nome" => "Brian Brobbey", "posicao" => "ATA"],
    ["nome" => "Wilson Isidor", "posicao" => "ATA"],

    // Burnley
    ["nome" => "Martin Dúbravka", "posicao" => "GOL"],
    ["nome" => "Kyle Walker", "posicao" => "LD"],
    ["nome" => "Maxime Estève", "posicao" => "ZAG"],
    ["nome" => "Josh Cullen", "posicao" => "VOL"],
    ["nome" => "Lesley Ugochukwu", "posicao" => "VOL"],
    ["nome" => "Zian Flemming", "posicao" => "MEI"],
    ["nome" => "Jaidon Anthony", "posicao" => "PD"],
    ["nome" => "Lyle Foster", "posicao" => "ATA"],
    ["nome" => "Zeki Amdouni", "posicao" => "ATA"],

    // ==================== LA LIGA ====================

    // Real Madrid
    ["nome" => "Thibaut Courtois", "posicao" => "GOL"],
    ["nome" => "Andriy Lunin", "posicao" => "GOL"],
    ["nome" => "Dean Huijsen", "posicao" => "ZAG"],
    ["nome" => "Éder Militão", "posicao" => "ZAG"],
    ["nome" => "Antonio Rüdiger", "posicao" => "ZAG"],
    ["nome" => "David Alaba", "posicao" => "ZAG"],
    ["nome" => "Raúl Asencio", "posicao" => "ZAG"],
    ["nome" => "Dani Carvajal", "posicao" => "LD"],
    ["nome" => "Trent Alexander-Arnold", "posicao" => "LD"],
    ["nome" => "Álvaro Carreras", "posicao" => "LE"],
    ["nome" => "Ferland Mendy", "posicao" => "LE"],
    ["nome" => "Fran García", "posicao" => "LE"],
    ["nome" => "Aurélien Tchouaméni", "posicao" => "VOL"],
    ["nome" => "Federico Valverde", "posicao" => "MC"],
    ["nome" => "Eduardo Camavinga", "posicao" => "MC"],
    ["nome" => "Dani Ceballos", "posicao" => "MC"],
    ["nome" => "Jude Bellingham", "posicao" => "MEI"],
    ["nome" => "Arda Güler", "posicao" => "MEI"],
    ["nome" => "Brahim Díaz", "posicao" => "MEI"],
    ["nome" => "Franco Mastantuono", "posicao" => "PD"],
    ["nome" => "Rodrygo", "posicao" => "PD"],
    ["nome" => "Vinícius Júnior", "posicao" => "PE"],
    ["nome" => "Kylian Mbappé", "posicao" => "ATA"],
    ["nome" => "Endrick", "posicao" => "ATA"],
    ["nome" => "Gonzalo García", "posicao" => "ATA"],

    // Barcelona
    ["nome" => "Joan García", "posicao" => "GOL"],
    ["nome" => "Wojciech Szczęsny", "posicao" => "GOL"],
    ["nome" => "Marc-André ter Stegen", "posicao" => "GOL"],
    ["nome" => "Pau Cubarsí", "posicao" => "ZAG"],
    ["nome" => "Ronald Araújo", "posicao" => "ZAG"],
    ["nome" => "Andreas Christensen", "posicao" => "ZAG"],
    ["nome" => "Eric García", "posicao" => "ZAG"],
    ["nome" => "Jules Koundé", "posicao" => "LD"],
    ["nome" => "Héctor Fort", "posicao" => "LD"],
    ["nome" => "Alejandro Balde", "posicao" => "LE"],
    ["nome" => "Gerard Martín", "posicao" => "LE"],
    ["nome" => "Marc Casadó", "posicao" => "VOL"],
    ["nome" => "Marc Bernal", "posicao" => "VOL"],
    ["nome" => "Frenkie de Jong", "posicao" => "MC"],
    ["nome" => "Pedri", "posicao" => "MC"],
    ["nome" => "Gavi", "posicao" => "MC"],
    ["nome" => "Dani Olmo", "posicao" => "MEI"],
    ["nome" => "Fermín López", "posicao" => "MEI"],
    ["nome" => "Lamine Yamal", "posicao" => "PD"],
    ["nome" => "Roony Bardghji", "posicao" => "PD"],
    ["nome" => "Raphinha", "posicao" => "PE"],
    ["nome" => "Marcus Rashford", "posicao" => "PE"],
    ["nome" => "Robert Lewandowski", "posicao" => "ATA"],
    ["nome" => "Ferran Torres", "posicao" => "ATA"],

    // Atlético de Madrid
    ["nome" => "Jan Oblak", "posicao" => "GOL"],
    ["nome" => "Juan Musso", "posicao" => "GOL"],
    ["nome" => "José María Giménez", "posicao" => "ZAG"],
    ["nome" => "Robin Le Normand", "posicao" => "ZAG"],
    ["nome" => "David Hancko", "posicao" => "ZAG"],
    ["nome" => "Clément Lenglet", "posicao" => "ZAG"],
    ["nome" => "Marcos Llorente", "posicao" => "LD"],
    ["nome" => "Nahuel Molina", "posicao" => "LD"],
    ["nome" => "Matteo Ruggeri", "posicao" => "LE"],
    ["nome" => "Johnny Cardoso", "posicao" => "VOL"],
    ["nome" => "Pablo Barrios", "posicao" => "MC"],
    ["nome" => "Koke", "posicao" => "MC"],
    ["nome" => "Rodrigo De Paul", "posicao" => "MC"],
    ["nome" => "Conor Gallagher", "posicao" => "MC"],
    ["nome" => "Álex Baena", "posicao" => "MEI"],
    ["nome" => "Thiago Almada", "posicao" => "MEI"],
    ["nome" => "Giuliano Simeone", "posicao" => "PD"],
    ["nome" => "Nicolás González", "posicao" => "PE"],
    ["nome" => "Antoine Griezmann", "posicao" => "ATA"],
    ["nome" => "Julián Álvarez", "posicao" => "ATA"],
    ["nome" => "Alexander Sørloth", "posicao" => "ATA"],
    ["nome" => "Giacomo Raspadori", "posicao" => "ATA"],

    // Athletic Club
    ["nome" => "Unai Simón", "posicao" => "GOL"],
    ["nome" => "Dani Vivian", "posicao" => "ZAG"],
    ["nome" => "Aymeric Laporte", "posicao" => "ZAG"],
    ["nome" => "Aitor Paredes", "posicao" => "ZAG"],
    ["nome" => "Iñigo Lekue", "posicao" => "LD"],
    ["nome" => "Yuri Berchiche", "posicao" => "LE"],
    ["nome" => "Mikel Jauregizar", "posicao" => "VOL"],
    ["nome" => "Beñat Prados", "posicao" => "VOL"],
    ["nome" => "Oihan Sancet", "posicao" => "MEI"],
    ["nome" => "Unai Gómez", "posicao" => "MEI"],
    ["nome" => "Nico Williams", "posicao" => "PE"],
    ["nome" => "Álex Berenguer", "posicao" => "PE"],
    ["nome" => "Iñaki Williams", "posicao" => "PD"],
    ["nome" => "Gorka Guruzeta", "posicao" => "ATA"],

    // Real Sociedad
    ["nome" => "Álex Remiro", "posicao" => "GOL"],
    ["nome" => "Igor Zubeldia", "posicao" => "ZAG"],
    ["nome" => "Jon Aramburu", "posicao" => "LD"],
    ["nome" => "Aihen Muñoz", "posicao" => "LE"],
    ["nome" => "Sergio Gómez", "posicao" => "LE"],
    ["nome" => "Yangel Herrera", "posicao" => "MC"],
    ["nome" => "Luka Sučić", "posicao" => "MC"],
    ["nome" => "Brais Méndez", "posicao" => "MEI"],
    ["nome" => "Takefusa Kubo", "posicao" => "PD"],
    ["nome" => "Gonçalo Guedes", "posicao" => "PD"],
    ["nome" => "Ander Barrenetxea", "posicao" => "PE"],
    ["nome" => "Orri Óskarsson", "posicao" => "ATA"],
    ["nome" => "Mikel Oyarzabal", "posicao" => "ATA"],

    // Villarreal
    ["nome" => "Luiz Júnior", "posicao" => "GOL"],
    ["nome" => "Juan Foyth", "posicao" => "ZAG"],
    ["nome" => "Rafa Marín", "posicao" => "ZAG"],
    ["nome" => "Logan Costa", "posicao" => "ZAG"],
    ["nome" => "Santiago Mouriño", "posicao" => "ZAG"],
    ["nome" => "Renato Veiga", "posicao" => "ZAG"],
    ["nome" => "Alfonso Pedraza", "posicao" => "LE"],
    ["nome" => "Pape Gueye", "posicao" => "VOL"],
    ["nome" => "Thomas Partey", "posicao" => "MC"],
    ["nome" => "Santi Comesaña", "posicao" => "MC"],
    ["nome" => "Dani Parejo", "posicao" => "MC"],
    ["nome" => "Alberto Moleiro", "posicao" => "MEI"],
    ["nome" => "Ayoze Pérez", "posicao" => "MEI"],
    ["nome" => "Nicolas Pépé", "posicao" => "PD"],
    ["nome" => "Tajon Buchanan", "posicao" => "PD"],
    ["nome" => "Yéremy Pino", "posicao" => "PE"],
    ["nome" => "Gerard Moreno", "posicao" => "ATA"],
    ["nome" => "Georges Mikautadze", "posicao" => "ATA"],

    // Real Betis
    ["nome" => "Álvaro Valles", "posicao" => "GOL"],
    ["nome" => "Marc Bartra", "posicao" => "ZAG"],
    ["nome" => "Natan", "posicao" => "ZAG"],
    ["nome" => "Diego Llorente", "posicao" => "ZAG"],
    ["nome" => "Héctor Bellerín", "posicao" => "LD"],
    ["nome" => "Junior Firpo", "posicao" => "LE"],
    ["nome" => "Ricardo Rodríguez", "posicao" => "LE"],
    ["nome" => "Sofyan Amrabat", "posicao" => "VOL"],
    ["nome" => "Marc Roca", "posicao" => "VOL"],
    ["nome" => "Pablo Fornals", "posicao" => "MEI"],
    ["nome" => "Giovani Lo Celso", "posicao" => "MEI"],
    ["nome" => "Isco", "posicao" => "MEI"],
    ["nome" => "Antony", "posicao" => "PD"],
    ["nome" => "Abde Ezzalzouli", "posicao" => "PE"],
    ["nome" => "Cucho Hernández", "posicao" => "ATA"],
    ["nome" => "Chimy Ávila", "posicao" => "ATA"],

    // Sevilla
    ["nome" => "Nemanja Gudelj", "posicao" => "VOL"],
    ["nome" => "Lucien Agoumé", "posicao" => "VOL"],
    ["nome" => "Loïc Badé", "posicao" => "ZAG"],
    ["nome" => "Kike Salas", "posicao" => "ZAG"],
    ["nome" => "Adrià Pedrosa", "posicao" => "LE"],
    ["nome" => "José Ángel Carmona", "posicao" => "LD"],
    ["nome" => "Djibril Sow", "posicao" => "MC"],
    ["nome" => "Chidera Ejuke", "posicao" => "PE"],
    ["nome" => "Alexis Sánchez", "posicao" => "ATA"],
    ["nome" => "Isaac Romero", "posicao" => "ATA"],
    ["nome" => "Akor Adams", "posicao" => "ATA"],

    // Valencia
    ["nome" => "Stole Dimitrievski", "posicao" => "GOL"],
    ["nome" => "Mouctar Diakhaby", "posicao" => "ZAG"],
    ["nome" => "César Tárrega", "posicao" => "ZAG"],
    ["nome" => "José Gayà", "posicao" => "LE"],
    ["nome" => "Dimitri Foulquier", "posicao" => "LD"],
    ["nome" => "Pepelu", "posicao" => "VOL"],
    ["nome" => "Javi Guerra", "posicao" => "MC"],
    ["nome" => "André Almeida", "posicao" => "MEI"],
    ["nome" => "Diego López", "posicao" => "PD"],
    ["nome" => "Largie Ramazani", "posicao" => "PD"],
    ["nome" => "Luis Rioja", "posicao" => "PE"],
    ["nome" => "Hugo Duro", "posicao" => "ATA"],

    // Outros da La Liga
    ["nome" => "Ladislav Krejčí", "posicao" => "ZAG"],
    ["nome" => "Arnau Martínez", "posicao" => "LD"],
    ["nome" => "Azzedine Ounahi", "posicao" => "MC"],
    ["nome" => "Viktor Tsygankov", "posicao" => "PD"],
    ["nome" => "Bryan Gil", "posicao" => "PE"],
    ["nome" => "Vladyslav Vanat", "posicao" => "ATA"],
    ["nome" => "Carl Starfelt", "posicao" => "ZAG"],
    ["nome" => "Marcos Alonso", "posicao" => "LE"],
    ["nome" => "Fran Beltrán", "posicao" => "VOL"],
    ["nome" => "Ilaix Moriba", "posicao" => "MC"],
    ["nome" => "Williot Swedberg", "posicao" => "PD"],
    ["nome" => "Hugo Álvarez", "posicao" => "PE"],
    ["nome" => "Iago Aspas", "posicao" => "ATA"],
    ["nome" => "Borja Iglesias", "posicao" => "ATA"],
    ["nome" => "Jesús Areso", "posicao" => "LD"],
    ["nome" => "Aimar Oroz", "posicao" => "MEI"],
    ["nome" => "Bryan Zaragoza", "posicao" => "PE"],
    ["nome" => "Rubén García", "posicao" => "PD"],
    ["nome" => "Ante Budimir", "posicao" => "ATA"],
    ["nome" => "Dominik Greif", "posicao" => "GOL"],
    ["nome" => "Pablo Maffeo", "posicao" => "LD"],
    ["nome" => "Antonio Raíllo", "posicao" => "ZAG"],
    ["nome" => "Samú Costa", "posicao" => "VOL"],
    ["nome" => "Sergi Darder", "posicao" => "MC"],
    ["nome" => "Jan Virgili", "posicao" => "PE"],
    ["nome" => "Takuma Asano", "posicao" => "PE"],
    ["nome" => "Vedat Muriqi", "posicao" => "ATA"],
    ["nome" => "Andrei Rațiu", "posicao" => "LD"],
    ["nome" => "Unai López", "posicao" => "MC"],
    ["nome" => "Isi Palazón", "posicao" => "MEI"],
    ["nome" => "Jorge de Frutos", "posicao" => "PD"],
    ["nome" => "Álvaro García", "posicao" => "PE"],
    ["nome" => "Sergio Camello", "posicao" => "ATA"],
    ["nome" => "David Soria", "posicao" => "GOL"],
    ["nome" => "Djené", "posicao" => "ZAG"],
    ["nome" => "Mauro Arambarri", "posicao" => "MC"],
    ["nome" => "Carles Aleñá", "posicao" => "MEI"],
    ["nome" => "Borja Mayoral", "posicao" => "ATA"],
    ["nome" => "Christantus Uche", "posicao" => "ATA"],
    ["nome" => "Antonio Blanco", "posicao" => "VOL"],
    ["nome" => "Carlos Vicente", "posicao" => "PD"],
    ["nome" => "Toni Martínez", "posicao" => "ATA"],
    ["nome" => "Leandro Cabrera", "posicao" => "ZAG"],
    ["nome" => "Carlos Romero", "posicao" => "LE"],
    ["nome" => "Edu Expósito", "posicao" => "MC"],
    ["nome" => "Javi Puado", "posicao" => "ATA"],
    ["nome" => "Álvaro Rodríguez", "posicao" => "ATA"],
    ["nome" => "Rafa Mir", "posicao" => "ATA"],
    ["nome" => "Santi Cazorla", "posicao" => "MEI"],
    ["nome" => "Salomón Rondón", "posicao" => "ATA"],
    ["nome" => "Iván Romero", "posicao" => "PD"],

    // ==================== SERIE A ====================

    // Inter de Milão
    ["nome" => "Yann Sommer", "posicao" => "GOL"],
    ["nome" => "Alessandro Bastoni", "posicao" => "ZAG"],
    ["nome" => "Francesco Acerbi", "posicao" => "ZAG"],
    ["nome" => "Stefan de Vrij", "posicao" => "ZAG"],
    ["nome" => "Yann Bisseck", "posicao" => "ZAG"],
    ["nome" => "Denzel Dumfries", "posicao" => "LD"],
    ["nome" => "Federico Dimarco", "posicao" => "LE"],
    ["nome" => "Carlos Augusto", "posicao" => "LE"],
    ["nome" => "Hakan Çalhanoğlu", "posicao" => "VOL"],
    ["nome" => "Nicolò Barella", "posicao" => "MC"],
    ["nome" => "Henrikh Mkhitaryan", "posicao" => "MC"],
    ["nome" => "Piotr Zieliński", "posicao" => "MC"],
    ["nome" => "Davide Frattesi", "posicao" => "MC"],
    ["nome" => "Petar Sučić", "posicao" => "MC"],
    ["nome" => "Kristjan Asllani", "posicao" => "MC"],
    ["nome" => "Luis Henrique", "posicao" => "PD"],
    ["nome" => "Lautaro Martínez", "posicao" => "ATA"],
    ["nome" => "Marcus Thuram", "posicao" => "ATA"],
    ["nome" => "Ange-Yoan Bonny", "posicao" => "ATA"],
    ["nome" => "Francesco Pio Esposito", "posicao" => "ATA"],

    // Milan
    ["nome" => "Mike Maignan", "posicao" => "GOL"],
    ["nome" => "Fikayo Tomori", "posicao" => "ZAG"],
    ["nome" => "Strahinja Pavlović", "posicao" => "ZAG"],
    ["nome" => "Matteo Gabbia", "posicao" => "ZAG"],
    ["nome" => "Koni De Winter", "posicao" => "ZAG"],
    ["nome" => "Emerson Royal", "posicao" => "LD"],
    ["nome" => "Zachary Athekame", "posicao" => "LD"],
    ["nome" => "Davide Bartesaghi", "posicao" => "LE"],
    ["nome" => "Samuele Ricci", "posicao" => "VOL"],
    ["nome" => "Luka Modrić", "posicao" => "MC"],
    ["nome" => "Adrien Rabiot", "posicao" => "MC"],
    ["nome" => "Youssouf Fofana", "posicao" => "MC"],
    ["nome" => "Ruben Loftus-Cheek", "posicao" => "MC"],
    ["nome" => "Ardon Jashari", "posicao" => "MC"],
    ["nome" => "Alexis Saelemaekers", "posicao" => "PD"],
    ["nome" => "Christian Pulisic", "posicao" => "PE"],
    ["nome" => "Rafael Leão", "posicao" => "PE"],
    ["nome" => "Santiago Giménez", "posicao" => "ATA"],
    ["nome" => "Christopher Nkunku", "posicao" => "ATA"],

    // Juventus
    ["nome" => "Michele Di Gregorio", "posicao" => "GOL"],
    ["nome" => "Gleison Bremer", "posicao" => "ZAG"],
    ["nome" => "Federico Gatti", "posicao" => "ZAG"],
    ["nome" => "Pierre Kalulu", "posicao" => "ZAG"],
    ["nome" => "Lloyd Kelly", "posicao" => "ZAG"],
    ["nome" => "Juan Cabal", "posicao" => "LD"],
    ["nome" => "Emil Holm", "posicao" => "LD"],
    ["nome" => "Andrea Cambiaso", "posicao" => "LE"],
    ["nome" => "Manuel Locatelli", "posicao" => "VOL"],
    ["nome" => "Khéphren Thuram", "posicao" => "MC"],
    ["nome" => "Weston McKennie", "posicao" => "MC"],
    ["nome" => "Teun Koopmeiners", "posicao" => "MC"],
    ["nome" => "Douglas Luiz", "posicao" => "MC"],
    ["nome" => "Kenan Yıldız", "posicao" => "PE"],
    ["nome" => "Francisco Conceição", "posicao" => "PD"],
    ["nome" => "Edon Zhegrova", "posicao" => "PD"],
    ["nome" => "Jonathan David", "posicao" => "ATA"],
    ["nome" => "Dušan Vlahović", "posicao" => "ATA"],
    ["nome" => "Loïs Openda", "posicao" => "ATA"],

    // Napoli
    ["nome" => "Alex Meret", "posicao" => "GOL"],
    ["nome" => "Vanja Milinković-Savić", "posicao" => "GOL"],
    ["nome" => "Alessandro Buongiorno", "posicao" => "ZAG"],
    ["nome" => "Amir Rrahmani", "posicao" => "ZAG"],
    ["nome" => "Sam Beukema", "posicao" => "ZAG"],
    ["nome" => "Giovanni Di Lorenzo", "posicao" => "LD"],
    ["nome" => "Leonardo Spinazzola", "posicao" => "LE"],
    ["nome" => "Mathías Olivera", "posicao" => "LE"],
    ["nome" => "Miguel Gutiérrez", "posicao" => "LE"],
    ["nome" => "Stanislav Lobotka", "posicao" => "VOL"],
    ["nome" => "Scott McTominay", "posicao" => "MC"],
    ["nome" => "Billy Gilmour", "posicao" => "MC"],
    ["nome" => "Frank Anguissa", "posicao" => "MC"],
    ["nome" => "Kevin De Bruyne", "posicao" => "MEI"],
    ["nome" => "Antonio Vergara", "posicao" => "MEI"],
    ["nome" => "David Neres", "posicao" => "PD"],
    ["nome" => "Matteo Politano", "posicao" => "PD"],
    ["nome" => "Noa Lang", "posicao" => "PE"],
    ["nome" => "Romelu Lukaku", "posicao" => "ATA"],
    ["nome" => "Rasmus Højlund", "posicao" => "ATA"],

    // Atalanta
    ["nome" => "Marco Carnesecchi", "posicao" => "GOL"],
    ["nome" => "Berat Djimsiti", "posicao" => "ZAG"],
    ["nome" => "Isak Hien", "posicao" => "ZAG"],
    ["nome" => "Giorgio Scalvini", "posicao" => "ZAG"],
    ["nome" => "Odilon Kossounou", "posicao" => "ZAG"],
    ["nome" => "Sead Kolašinac", "posicao" => "ZAG"],
    ["nome" => "Raoul Bellanova", "posicao" => "LD"],
    ["nome" => "Davide Zappacosta", "posicao" => "LD"],
    ["nome" => "Marten de Roon", "posicao" => "VOL"],
    ["nome" => "Éderson", "posicao" => "MC"],
    ["nome" => "Mario Pašalić", "posicao" => "MC"],
    ["nome" => "Yunus Musah", "posicao" => "MC"],
    ["nome" => "Lazar Samardžić", "posicao" => "MEI"],
    ["nome" => "Charles De Ketelaere", "posicao" => "MEI"],
    ["nome" => "Ademola Lookman", "posicao" => "PE"],
    ["nome" => "Gianluca Scamacca", "posicao" => "ATA"],
    ["nome" => "Nikola Krstović", "posicao" => "ATA"],

    // Roma
    ["nome" => "Mile Svilar", "posicao" => "GOL"],
    ["nome" => "Gianluca Mancini", "posicao" => "ZAG"],
    ["nome" => "Evan Ndicka", "posicao" => "ZAG"],
    ["nome" => "Mario Hermoso", "posicao" => "ZAG"],
    ["nome" => "Wesley França", "posicao" => "LD"],
    ["nome" => "Zeki Çelik", "posicao" => "LD"],
    ["nome" => "Angeliño", "posicao" => "LE"],
    ["nome" => "Manu Koné", "posicao" => "MC"],
    ["nome" => "Bryan Cristante", "posicao" => "MC"],
    ["nome" => "Neil El Aynaoui", "posicao" => "MC"],
    ["nome" => "Niccolò Pisilli", "posicao" => "MC"],
    ["nome" => "Lorenzo Pellegrini", "posicao" => "MEI"],
    ["nome" => "Paulo Dybala", "posicao" => "MEI"],
    ["nome" => "Tommaso Baldanzi", "posicao" => "MEI"],
    ["nome" => "Matías Soulé", "posicao" => "PD"],
    ["nome" => "Stephan El Shaarawy", "posicao" => "PE"],
    ["nome" => "Artem Dovbyk", "posicao" => "ATA"],
    ["nome" => "Evan Ferguson", "posicao" => "ATA"],

    // Lazio
    ["nome" => "Ivan Provedel", "posicao" => "GOL"],
    ["nome" => "Alessio Romagnoli", "posicao" => "ZAG"],
    ["nome" => "Mario Gila", "posicao" => "ZAG"],
    ["nome" => "Adam Marušić", "posicao" => "LD"],
    ["nome" => "Nuno Tavares", "posicao" => "LE"],
    ["nome" => "Nicolò Rovella", "posicao" => "VOL"],
    ["nome" => "Mattéo Guendouzi", "posicao" => "MC"],
    ["nome" => "Danilo Cataldi", "posicao" => "MC"],
    ["nome" => "Gustav Isaksen", "posicao" => "PD"],
    ["nome" => "Matteo Cancellieri", "posicao" => "PD"],
    ["nome" => "Pedro", "posicao" => "PD"],
    ["nome" => "Mattia Zaccagni", "posicao" => "PE"],
    ["nome" => "Boulaye Dia", "posicao" => "ATA"],
    ["nome" => "Taty Castellanos", "posicao" => "ATA"],

    // Fiorentina
    ["nome" => "David de Gea", "posicao" => "GOL"],
    ["nome" => "Pietro Comuzzo", "posicao" => "ZAG"],
    ["nome" => "Luca Ranieri", "posicao" => "ZAG"],
    ["nome" => "Dodô", "posicao" => "LD"],
    ["nome" => "Robin Gosens", "posicao" => "LE"],
    ["nome" => "Rolando Mandragora", "posicao" => "MC"],
    ["nome" => "Nicolò Fagioli", "posicao" => "MC"],
    ["nome" => "Cher Ndour", "posicao" => "MC"],
    ["nome" => "Albert Guðmundsson", "posicao" => "MEI"],
    ["nome" => "Nicolò Zaniolo", "posicao" => "MEI"],
    ["nome" => "Moise Kean", "posicao" => "ATA"],

    // Bologna
    ["nome" => "Łukasz Skorupski", "posicao" => "GOL"],
    ["nome" => "Jhon Lucumí", "posicao" => "ZAG"],
    ["nome" => "Torbjörn Heggem", "posicao" => "ZAG"],
    ["nome" => "Stefan Posch", "posicao" => "LD"],
    ["nome" => "Juan Miranda", "posicao" => "LE"],
    ["nome" => "Lewis Ferguson", "posicao" => "MC"],
    ["nome" => "Remo Freuler", "posicao" => "MC"],
    ["nome" => "Nikola Moro", "posicao" => "MC"],
    ["nome" => "Riccardo Orsolini", "posicao" => "PD"],
    ["nome" => "Santiago Castro", "posicao" => "ATA"],
    ["nome" => "Jens Odgaard", "posicao" => "ATA"],
    ["nome" => "Thijs Dallinga", "posicao" => "ATA"],

    // Outros da Serie A
    ["nome" => "Perr Schuurs", "posicao" => "ZAG"],
    ["nome" => "Nikola Vlašić", "posicao" => "MEI"],
    ["nome" => "Duván Zapata", "posicao" => "ATA"],
    ["nome" => "Che Adams", "posicao" => "ATA"],
    ["nome" => "Giovanni Simeone", "posicao" => "ATA"],
    ["nome" => "Oumar Solet", "posicao" => "ZAG"],
    ["nome" => "Jesper Karlström", "posicao" => "MC"],
    ["nome" => "Florian Thauvin", "posicao" => "MEI"],
    ["nome" => "Leo Østigård", "posicao" => "ZAG"],
    ["nome" => "Morten Frendrup", "posicao" => "MC"],
    ["nome" => "Ruslan Malinovskyi", "posicao" => "MEI"],
    ["nome" => "Junior Messias", "posicao" => "PD"],
    ["nome" => "Jean Butez", "posicao" => "GOL"],
    ["nome" => "Marc-Oliver Kempf", "posicao" => "ZAG"],
    ["nome" => "Álex Valle", "posicao" => "LE"],
    ["nome" => "Maxence Caqueret", "posicao" => "MC"],
    ["nome" => "Lucas Da Cunha", "posicao" => "MC"],
    ["nome" => "Sergi Roberto", "posicao" => "MC"],
    ["nome" => "Nico Paz", "posicao" => "MEI"],
    ["nome" => "Jesús Rodríguez", "posicao" => "PD"],
    ["nome" => "Assane Diao", "posicao" => "PD"],
    ["nome" => "Anastasios Douvikas", "posicao" => "ATA"],
    ["nome" => "Álvaro Morata", "posicao" => "ATA"],
    ["nome" => "Zion Suzuki", "posicao" => "GOL"],
    ["nome" => "Emanuele Valeri", "posicao" => "LE"],
    ["nome" => "Dennis Man", "posicao" => "PD"],
    ["nome" => "Mateo Pellegrino", "posicao" => "ATA"],
    ["nome" => "Elia Caprile", "posicao" => "GOL"],
    ["nome" => "Marco Palestra", "posicao" => "LD"],
    ["nome" => "Sebastiano Esposito", "posicao" => "ATA"],
    ["nome" => "Jay Idzes", "posicao" => "ZAG"],
    ["nome" => "Kristian Thorstvedt", "posicao" => "MC"],
    ["nome" => "Domenico Berardi", "posicao" => "PD"],
    ["nome" => "Armand Laurienté", "posicao" => "PE"],
    ["nome" => "Andrea Pinamonti", "posicao" => "ATA"],
    ["nome" => "Emil Audero", "posicao" => "GOL"],
    ["nome" => "Jamie Vardy", "posicao" => "ATA"],
    ["nome" => "Lameck Banda", "posicao" => "PD"],
    ["nome" => "Francesco Camarda", "posicao" => "ATA"],
    ["nome" => "Marius Marin", "posicao" => "MC"],
    ["nome" => "Stefano Moreo", "posicao" => "ATA"],

    // ==================== BUNDESLIGA ====================

    // Bayern de Munique
    ["nome" => "Manuel Neuer", "posicao" => "GOL"],
    ["nome" => "Jonas Urbig", "posicao" => "GOL"],
    ["nome" => "Dayot Upamecano", "posicao" => "ZAG"],
    ["nome" => "Kim Min-jae", "posicao" => "ZAG"],
    ["nome" => "Jonathan Tah", "posicao" => "ZAG"],
    ["nome" => "Hiroki Ito", "posicao" => "ZAG"],
    ["nome" => "Konrad Laimer", "posicao" => "LD"],
    ["nome" => "Josip Stanišić", "posicao" => "LD"],
    ["nome" => "Alphonso Davies", "posicao" => "LE"],
    ["nome" => "Raphaël Guerreiro", "posicao" => "LE"],
    ["nome" => "Joshua Kimmich", "posicao" => "VOL"],
    ["nome" => "Aleksandar Pavlović", "posicao" => "VOL"],
    ["nome" => "Leon Goretzka", "posicao" => "MC"],
    ["nome" => "Tom Bischof", "posicao" => "MC"],
    ["nome" => "Jamal Musiala", "posicao" => "MEI"],
    ["nome" => "Lennart Karl", "posicao" => "MEI"],
    ["nome" => "Michael Olise", "posicao" => "PD"],
    ["nome" => "Serge Gnabry", "posicao" => "PD"],
    ["nome" => "Luis Díaz", "posicao" => "PE"],
    ["nome" => "Harry Kane", "posicao" => "ATA"],

    // Borussia Dortmund
    ["nome" => "Gregor Kobel", "posicao" => "GOL"],
    ["nome" => "Nico Schlotterbeck", "posicao" => "ZAG"],
    ["nome" => "Waldemar Anton", "posicao" => "ZAG"],
    ["nome" => "Niklas Süle", "posicao" => "ZAG"],
    ["nome" => "Julian Ryerson", "posicao" => "LD"],
    ["nome" => "Yan Couto", "posicao" => "LD"],
    ["nome" => "Daniel Svensson", "posicao" => "LE"],
    ["nome" => "Ramy Bensebaini", "posicao" => "LE"],
    ["nome" => "Emre Can", "posicao" => "VOL"],
    ["nome" => "Pascal Groß", "posicao" => "MC"],
    ["nome" => "Felix Nmecha", "posicao" => "MC"],
    ["nome" => "Marcel Sabitzer", "posicao" => "MC"],
    ["nome" => "Jobe Bellingham", "posicao" => "MC"],
    ["nome" => "Julian Brandt", "posicao" => "MEI"],
    ["nome" => "Carney Chukwuemeka", "posicao" => "MEI"],
    ["nome" => "Karim Adeyemi", "posicao" => "PE"],
    ["nome" => "Serhou Guirassy", "posicao" => "ATA"],
    ["nome" => "Maximilian Beier", "posicao" => "ATA"],
    ["nome" => "Fábio Silva", "posicao" => "ATA"],

    // Bayer Leverkusen
    ["nome" => "Mark Flekken", "posicao" => "GOL"],
    ["nome" => "Jarell Quansah", "posicao" => "ZAG"],
    ["nome" => "Edmond Tapsoba", "posicao" => "ZAG"],
    ["nome" => "Piero Hincapié", "posicao" => "ZAG"],
    ["nome" => "Jeanuël Belocian", "posicao" => "ZAG"],
    ["nome" => "Arthur", "posicao" => "LD"],
    ["nome" => "Álex Grimaldo", "posicao" => "LE"],
    ["nome" => "Robert Andrich", "posicao" => "VOL"],
    ["nome" => "Exequiel Palacios", "posicao" => "MC"],
    ["nome" => "Aleix García", "posicao" => "MC"],
    ["nome" => "Ibrahim Maza", "posicao" => "MEI"],
    ["nome" => "Malik Tillman", "posicao" => "MEI"],
    ["nome" => "Nathan Tella", "posicao" => "PD"],
    ["nome" => "Eliesse Ben Seghir", "posicao" => "PE"],
    ["nome" => "Patrik Schick", "posicao" => "ATA"],
    ["nome" => "Christian Kofane", "posicao" => "ATA"],
    ["nome" => "Victor Boniface", "posicao" => "ATA"],

    // RB Leipzig
    ["nome" => "Péter Gulácsi", "posicao" => "GOL"],
    ["nome" => "Willi Orbán", "posicao" => "ZAG"],
    ["nome" => "Castello Lukeba", "posicao" => "ZAG"],
    ["nome" => "El Chadaille Bitshiabu", "posicao" => "ZAG"],
    ["nome" => "Lutsharel Geertruida", "posicao" => "ZAG"],
    ["nome" => "Ridle Baku", "posicao" => "LD"],
    ["nome" => "David Raum", "posicao" => "LE"],
    ["nome" => "Xaver Schlager", "posicao" => "VOL"],
    ["nome" => "Nicolas Seiwald", "posicao" => "VOL"],
    ["nome" => "Assan Ouédraogo", "posicao" => "MC"],
    ["nome" => "Eljif Elmas", "posicao" => "MC"],
    ["nome" => "Christoph Baumgartner", "posicao" => "MEI"],
    ["nome" => "Antonio Nusa", "posicao" => "PE"],
    ["nome" => "Yan Diomande", "posicao" => "PE"],
    ["nome" => "Johan Bakayoko", "posicao" => "PD"],
    ["nome" => "Conrad Harder", "posicao" => "ATA"],

    // Eintracht Frankfurt
    ["nome" => "Kevin Trapp", "posicao" => "GOL"],
    ["nome" => "Robin Koch", "posicao" => "ZAG"],
    ["nome" => "Nnamdi Collins", "posicao" => "ZAG"],
    ["nome" => "Rasmus Kristensen", "posicao" => "LD"],
    ["nome" => "Nathaniel Brown", "posicao" => "LE"],
    ["nome" => "Ellyes Skhiri", "posicao" => "VOL"],
    ["nome" => "Hugo Larsson", "posicao" => "MC"],
    ["nome" => "Mario Götze", "posicao" => "MEI"],
    ["nome" => "Can Uzun", "posicao" => "MEI"],
    ["nome" => "Ansgar Knauff", "posicao" => "PD"],
    ["nome" => "Jean-Matteo Bahoya", "posicao" => "PE"],
    ["nome" => "Jonathan Burkardt", "posicao" => "ATA"],

    // VfB Stuttgart
    ["nome" => "Alexander Nübel", "posicao" => "GOL"],
    ["nome" => "Ramon Hendriks", "posicao" => "ZAG"],
    ["nome" => "Jeff Chabot", "posicao" => "ZAG"],
    ["nome" => "Josha Vagnoman", "posicao" => "LD"],
    ["nome" => "Maximilian Mittelstädt", "posicao" => "LE"],
    ["nome" => "Angelo Stiller", "posicao" => "VOL"],
    ["nome" => "Atakan Karazor", "posicao" => "VOL"],
    ["nome" => "Enzo Millot", "posicao" => "MEI"],
    ["nome" => "Bilal El Khannouss", "posicao" => "MEI"],
    ["nome" => "Chris Führich", "posicao" => "PE"],
    ["nome" => "Jamie Leweling", "posicao" => "PD"],
    ["nome" => "Deniz Undav", "posicao" => "ATA"],
    ["nome" => "Ermedin Demirović", "posicao" => "ATA"],

    // Outros da Bundesliga
    ["nome" => "Noah Atubolu", "posicao" => "GOL"],
    ["nome" => "Matthias Ginter", "posicao" => "ZAG"],
    ["nome" => "Philipp Lienhart", "posicao" => "ZAG"],
    ["nome" => "Maximilian Eggestein", "posicao" => "MC"],
    ["nome" => "Johan Manzambi", "posicao" => "MC"],
    ["nome" => "Ritsu Doan", "posicao" => "PD"],
    ["nome" => "Vincenzo Grifo", "posicao" => "PE"],
    ["nome" => "Lucas Höler", "posicao" => "ATA"],
    ["nome" => "Nico Elvedi", "posicao" => "ZAG"],
    ["nome" => "Joe Scally", "posicao" => "LD"],
    ["nome" => "Luca Netz", "posicao" => "LE"],
    ["nome" => "Rocco Reitz", "posicao" => "MC"],
    ["nome" => "Kevin Stöger", "posicao" => "MEI"],
    ["nome" => "Franck Honorat", "posicao" => "PD"],
    ["nome" => "Tim Kleindienst", "posicao" => "ATA"],
    ["nome" => "Kamil Grabara", "posicao" => "GOL"],
    ["nome" => "Konstantinos Koulierakis", "posicao" => "ZAG"],
    ["nome" => "Maximilian Arnold", "posicao" => "MC"],
    ["nome" => "Christian Eriksen", "posicao" => "MEI"],
    ["nome" => "Lovro Majer", "posicao" => "MEI"],
    ["nome" => "Patrick Wimmer", "posicao" => "PD"],
    ["nome" => "Vaclav Cerny", "posicao" => "PD"],
    ["nome" => "Mohamed Amoura", "posicao" => "PE"],
    ["nome" => "Jonas Wind", "posicao" => "ATA"],
    ["nome" => "Danilho Doekhi", "posicao" => "ZAG"],
    ["nome" => "Rani Khedira", "posicao" => "VOL"],
    ["nome" => "Andras Schäfer", "posicao" => "MC"],
    ["nome" => "Yorbe Vertessen", "posicao" => "ATA"],
    ["nome" => "Silvan Widmer", "posicao" => "LD"],
    ["nome" => "Nadiem Amiri", "posicao" => "MEI"],
    ["nome" => "Paul Nebel", "posicao" => "MEI"],
    ["nome" => "Marco Friedl", "posicao" => "ZAG"],
    ["nome" => "Yukinari Sugawara", "posicao" => "LD"],
    ["nome" => "Derrick Köhn", "posicao" => "LE"],
    ["nome" => "Jens Stage", "posicao" => "MC"],
    ["nome" => "Romano Schmid", "posicao" => "MEI"],
    ["nome" => "Justin Njinmah", "posicao" => "PE"],
    ["nome" => "Marvin Ducksch", "posicao" => "ATA"],
    ["nome" => "Oliver Baumann", "posicao" => "GOL"],
    ["nome" => "Grischa Prömel", "posicao" => "VOL"],
    ["nome" => "Alexander Prass", "posicao" => "MEI"],
    ["nome" => "Adam Hložek", "posicao" => "PD"],
    ["nome" => "Bazoumana Touré", "posicao" => "PE"],
    ["nome" => "Andrej Kramarić", "posicao" => "ATA"],
    ["nome" => "Wout Weghorst", "posicao" => "ATA"],
    ["nome" => "Fisnik Asllani", "posicao" => "ATA"],
    ["nome" => "Fabian Rieder", "posicao" => "MEI"],
    ["nome" => "Said El Mala", "posicao" => "PE"],
    ["nome" => "Jan Thielmann", "posicao" => "PD"],
    ["nome" => "Ragnar Ache", "posicao" => "ATA"],

    // ==================== LIGUE 1 ====================

    // Paris Saint-Germain
    ["nome" => "Lucas Chevalier", "posicao" => "GOL"],
    ["nome" => "Matvey Safonov", "posicao" => "GOL"],
    ["nome" => "Marquinhos", "posicao" => "ZAG"],
    ["nome" => "Willian Pacho", "posicao" => "ZAG"],
    ["nome" => "Lucas Beraldo", "posicao" => "ZAG"],
    ["nome" => "Illia Zabarnyi", "posicao" => "ZAG"],
    ["nome" => "Lucas Hernández", "posicao" => "ZAG"],
    ["nome" => "Achraf Hakimi", "posicao" => "LD"],
    ["nome" => "Nuno Mendes", "posicao" => "LE"],
    ["nome" => "Vitinha", "posicao" => "MC"],
    ["nome" => "João Neves", "posicao" => "MC"],
    ["nome" => "Fabián Ruiz", "posicao" => "MC"],
    ["nome" => "Warren Zaïre-Emery", "posicao" => "MC"],
    ["nome" => "Lee Kang-in", "posicao" => "MEI"],
    ["nome" => "Senny Mayulu", "posicao" => "MEI"],
    ["nome" => "Ousmane Dembélé", "posicao" => "PD"],
    ["nome" => "Désiré Doué", "posicao" => "PD"],
    ["nome" => "Bradley Barcola", "posicao" => "PE"],
    ["nome" => "Khvicha Kvaratskhelia", "posicao" => "PE"],
    ["nome" => "Gonçalo Ramos", "posicao" => "ATA"],

    // Olympique de Marselha
    ["nome" => "Geronimo Rulli", "posicao" => "GOL"],
    ["nome" => "Leonardo Balerdi", "posicao" => "ZAG"],
    ["nome" => "Facundo Medina", "posicao" => "ZAG"],
    ["nome" => "CJ Egan-Riley", "posicao" => "ZAG"],
    ["nome" => "Nayef Aguerd", "posicao" => "ZAG"],
    ["nome" => "Benjamin Pavard", "posicao" => "ZAG"],
    ["nome" => "Amir Murillo", "posicao" => "LD"],
    ["nome" => "Ulisses Garcia", "posicao" => "LE"],
    ["nome" => "Pierre-Emile Højbjerg", "posicao" => "VOL"],
    ["nome" => "Arthur Vermeeren", "posicao" => "VOL"],
    ["nome" => "Quinten Timber", "posicao" => "MC"],
    ["nome" => "Angel Gomes", "posicao" => "MC"],
    ["nome" => "Mason Greenwood", "posicao" => "PD"],
    ["nome" => "Timothy Weah", "posicao" => "PD"],
    ["nome" => "Igor Paixão", "posicao" => "PE"],
    ["nome" => "Jonathan Rowe", "posicao" => "PE"],
    ["nome" => "Amine Gouiri", "posicao" => "ATA"],

    // Monaco
    ["nome" => "Philipp Köhn", "posicao" => "GOL"],
    ["nome" => "Mohammed Salisu", "posicao" => "ZAG"],
    ["nome" => "Thilo Kehrer", "posicao" => "ZAG"],
    ["nome" => "Vanderson", "posicao" => "LD"],
    ["nome" => "Caio Henrique", "posicao" => "LE"],
    ["nome" => "Denis Zakaria", "posicao" => "VOL"],
    ["nome" => "Lamine Camara", "posicao" => "MC"],
    ["nome" => "Paul Pogba", "posicao" => "MC"],
    ["nome" => "Aleksandr Golovin", "posicao" => "MEI"],
    ["nome" => "Maghnes Akliouche", "posicao" => "MEI"],
    ["nome" => "Takumi Minamino", "posicao" => "PE"],
    ["nome" => "Ansu Fati", "posicao" => "PE"],
    ["nome" => "Krépin Diatta", "posicao" => "PD"],
    ["nome" => "Folarin Balogun", "posicao" => "ATA"],
    ["nome" => "Mika Biereth", "posicao" => "ATA"],
    ["nome" => "George Ilenikhena", "posicao" => "ATA"],

    // Lyon
    ["nome" => "Lucas Perri", "posicao" => "GOL"],
    ["nome" => "Moussa Niakhaté", "posicao" => "ZAG"],
    ["nome" => "Clinton Mata", "posicao" => "LD"],
    ["nome" => "Nicolás Tagliafico", "posicao" => "LE"],
    ["nome" => "Abner", "posicao" => "LE"],
    ["nome" => "Corentin Tolisso", "posicao" => "MC"],
    ["nome" => "Tyler Morton", "posicao" => "MC"],
    ["nome" => "Orel Mangala", "posicao" => "MC"],
    ["nome" => "Pavel Šulc", "posicao" => "MEI"],
    ["nome" => "Malick Fofana", "posicao" => "PE"],
    ["nome" => "Afonso Moreira", "posicao" => "PD"],
    ["nome" => "Alexandre Lacazette", "posicao" => "ATA"],

    // Lille
    ["nome" => "Berke Özer", "posicao" => "GOL"],
    ["nome" => "Aïssa Mandi", "posicao" => "ZAG"],
    ["nome" => "Nathan Ngoy", "posicao" => "ZAG"],
    ["nome" => "Chancel Mbemba", "posicao" => "ZAG"],
    ["nome" => "Benjamin André", "posicao" => "VOL"],
    ["nome" => "Ayyoub Bouaddi", "posicao" => "MC"],
    ["nome" => "Hákon Arnar Haraldsson", "posicao" => "MEI"],
    ["nome" => "Felix Correia", "posicao" => "PD"],
    ["nome" => "Matías Fernández-Pardo", "posicao" => "PE"],
    ["nome" => "Olivier Giroud", "posicao" => "ATA"],

    // Nice, Lens, Rennes, Strasbourg e outros
    ["nome" => "Marcin Bułka", "posicao" => "GOL"],
    ["nome" => "Jonathan Clauss", "posicao" => "LD"],
    ["nome" => "Moïse Bombito", "posicao" => "ZAG"],
    ["nome" => "Youssouf Ndayishimiye", "posicao" => "ZAG"],
    ["nome" => "Morgan Sanson", "posicao" => "MC"],
    ["nome" => "Sofiane Diop", "posicao" => "MEI"],
    ["nome" => "Jérémie Boga", "posicao" => "PE"],
    ["nome" => "Mohamed-Ali Cho", "posicao" => "PD"],
    ["nome" => "Terem Moffi", "posicao" => "ATA"],
    ["nome" => "Youssoufa Moukoko", "posicao" => "ATA"],
    ["nome" => "Brice Samba", "posicao" => "GOL"],
    ["nome" => "Ruben Aguilar", "posicao" => "LD"],
    ["nome" => "Matthieu Udol", "posicao" => "LE"],
    ["nome" => "Salis Abdul Samed", "posicao" => "VOL"],
    ["nome" => "Florian Sotoca", "posicao" => "PD"],
    ["nome" => "Wesley Saïd", "posicao" => "ATA"],
    ["nome" => "Jérémy Jacquet", "posicao" => "ZAG"],
    ["nome" => "Quentin Merlin", "posicao" => "LE"],
    ["nome" => "Benjamin Bourigeaud", "posicao" => "MC"],
    ["nome" => "Seko Fofana", "posicao" => "MC"],
    ["nome" => "Ludovic Blas", "posicao" => "MEI"],
    ["nome" => "Mousa Al-Tamari", "posicao" => "PD"],
    ["nome" => "Breel Embolo", "posicao" => "ATA"],
    ["nome" => "Mike Penders", "posicao" => "GOL"],
    ["nome" => "Guela Doué", "posicao" => "LD"],
    ["nome" => "Julio Enciso", "posicao" => "MEI"],
    ["nome" => "Diego Moreira", "posicao" => "PE"],
    ["nome" => "Sebastian Nanasi", "posicao" => "PE"],
    ["nome" => "Joaquín Panichelli", "posicao" => "ATA"],
    ["nome" => "Mark McKenzie", "posicao" => "ZAG"],
    ["nome" => "Junya Ito", "posicao" => "PD"],
    ["nome" => "Keito Nakamura", "posicao" => "PE"],
    ["nome" => "Mostafa Mohamed", "posicao" => "ATA"],

    // ==================== PORTUGAL ====================

    // Benfica
    ["nome" => "Anatoliy Trubin", "posicao" => "GOL"],
    ["nome" => "Nicolás Otamendi", "posicao" => "ZAG"],
    ["nome" => "António Silva", "posicao" => "ZAG"],
    ["nome" => "Tomás Araújo", "posicao" => "ZAG"],
    ["nome" => "Alexander Bah", "posicao" => "LD"],
    ["nome" => "Florentino Luís", "posicao" => "VOL"],
    ["nome" => "Fredrik Aursnes", "posicao" => "MC"],
    ["nome" => "Leandro Barreiro", "posicao" => "MC"],
    ["nome" => "Richard Ríos", "posicao" => "MC"],
    ["nome" => "Heorhiy Sudakov", "posicao" => "MEI"],
    ["nome" => "Dodi Lukébakio", "posicao" => "PD"],
    ["nome" => "Gianluca Prestianni", "posicao" => "PD"],
    ["nome" => "Kerem Aktürkoğlu", "posicao" => "PE"],
    ["nome" => "Andreas Schjelderup", "posicao" => "PE"],
    ["nome" => "Vangelis Pavlidis", "posicao" => "ATA"],
    ["nome" => "Arthur Cabral", "posicao" => "ATA"],

    // Sporting
    ["nome" => "Rui Silva", "posicao" => "GOL"],
    ["nome" => "Zeno Debast", "posicao" => "ZAG"],
    ["nome" => "Gonçalo Inácio", "posicao" => "ZAG"],
    ["nome" => "Ousmane Diomande", "posicao" => "ZAG"],
    ["nome" => "Eduardo Quaresma", "posicao" => "ZAG"],
    ["nome" => "Maxi Araújo", "posicao" => "LE"],
    ["nome" => "Nuno Santos", "posicao" => "LE"],
    ["nome" => "Morten Hjulmand", "posicao" => "VOL"],
    ["nome" => "Hidemasa Morita", "posicao" => "VOL"],
    ["nome" => "Giorgi Kochorashvili", "posicao" => "MC"],
    ["nome" => "Pedro Gonçalves", "posicao" => "MEI"],
    ["nome" => "Francisco Trincão", "posicao" => "PD"],
    ["nome" => "Geovany Quenda", "posicao" => "PD"],
    ["nome" => "Geny Catamo", "posicao" => "PD"],
    ["nome" => "Luis Javier Suárez", "posicao" => "ATA"],
    ["nome" => "Fotis Ioannidis", "posicao" => "ATA"],

    // Porto
    ["nome" => "Diogo Costa", "posicao" => "GOL"],
    ["nome" => "Jakub Kiwior", "posicao" => "ZAG"],
    ["nome" => "Nehuén Pérez", "posicao" => "ZAG"],
    ["nome" => "Alberto Costa", "posicao" => "LD"],
    ["nome" => "Francisco Moura", "posicao" => "LE"],
    ["nome" => "Alan Varela", "posicao" => "VOL"],
    ["nome" => "Victor Froholdt", "posicao" => "MC"],
    ["nome" => "Gabri Veiga", "posicao" => "MC"],
    ["nome" => "Stephen Eustáquio", "posicao" => "MC"],
    ["nome" => "Rodrigo Mora", "posicao" => "MEI"],
    ["nome" => "Fábio Vieira", "posicao" => "MEI"],
    ["nome" => "Pepê", "posicao" => "PD"],
    ["nome" => "William Gomes", "posicao" => "PE"],
    ["nome" => "Gonçalo Borges", "posicao" => "PE"],
    ["nome" => "Samu Aghehowa", "posicao" => "ATA"],
    ["nome" => "Deniz Gül", "posicao" => "ATA"],

    // Braga
    ["nome" => "Sikou Niakaté", "posicao" => "ZAG"],
    ["nome" => "Vitor Carvalho", "posicao" => "VOL"],
    ["nome" => "Ricardo Horta", "posicao" => "PE"],
    ["nome" => "Gabri Martínez", "posicao" => "PD"],
    ["nome" => "Álvaro Djaló", "posicao" => "PD"],
    ["nome" => "Amine El Ouazzani", "posicao" => "ATA"],

    // ==================== HOLANDA E BÉLGICA ====================

    // Ajax
    ["nome" => "Diant Ramaj", "posicao" => "GOL"],
    ["nome" => "Josip Šutalo", "posicao" => "ZAG"],
    ["nome" => "Youri Baas", "posicao" => "ZAG"],
    ["nome" => "Anton Gaaei", "posicao" => "LD"],
    ["nome" => "Jorthy Mokio", "posicao" => "MC"],
    ["nome" => "Kenneth Taylor", "posicao" => "MC"],
    ["nome" => "Davy Klaassen", "posicao" => "MC"],
    ["nome" => "Oscar Gloukh", "posicao" => "MEI"],
    ["nome" => "Mika Godts", "posicao" => "PE"],
    ["nome" => "Steven Berghuis", "posicao" => "PD"],

    // PSV
    ["nome" => "Matěj Kovář", "posicao" => "GOL"],
    ["nome" => "Ryan Flamingo", "posicao" => "ZAG"],
    ["nome" => "Sergiño Dest", "posicao" => "LD"],
    ["nome" => "Mauro Júnior", "posicao" => "LE"],
    ["nome" => "Jerdy Schouten", "posicao" => "VOL"],
    ["nome" => "Guus Til", "posicao" => "MEI"],
    ["nome" => "Ismael Saibari", "posicao" => "MEI"],
    ["nome" => "Couhaib Driouech", "posicao" => "PE"],
    ["nome" => "Ricardo Pepi", "posicao" => "ATA"],

    // Feyenoord e AZ
    ["nome" => "Timon Wellenrether", "posicao" => "GOL"],
    ["nome" => "Gernot Trauner", "posicao" => "ZAG"],
    ["nome" => "Hugo Bueno", "posicao" => "LE"],
    ["nome" => "Hwang In-beom", "posicao" => "MC"],
    ["nome" => "Jakub Moder", "posicao" => "MC"],
    ["nome" => "Calvin Stengs", "posicao" => "MEI"],
    ["nome" => "Luka Ivanušec", "posicao" => "MEI"],
    ["nome" => "Anis Hadj Moussa", "posicao" => "PD"],
    ["nome" => "Ayase Ueda", "posicao" => "ATA"],
    ["nome" => "Mees de Wit", "posicao" => "MEI"],
    ["nome" => "Sven Mijnans", "posicao" => "MEI"],
    ["nome" => "Troy Parrott", "posicao" => "ATA"],

    // Bélgica
    ["nome" => "Joel Ordóñez", "posicao" => "ZAG"],
    ["nome" => "Raphael Onyedika", "posicao" => "VOL"],
    ["nome" => "Hans Vanaken", "posicao" => "MEI"],
    ["nome" => "Carlos Forbs", "posicao" => "PE"],
    ["nome" => "Christos Tzolis", "posicao" => "PE"],
    ["nome" => "Romeo Vermant", "posicao" => "ATA"],
    ["nome" => "Jan Vertonghen", "posicao" => "ZAG"],
    ["nome" => "Mario Stroeykens", "posicao" => "MEI"],
    ["nome" => "Kasper Dolberg", "posicao" => "ATA"],
    ["nome" => "Luis Vázquez", "posicao" => "ATA"],
    ["nome" => "Konstantinos Karetsas", "posicao" => "MEI"],
    ["nome" => "Promise David", "posicao" => "ATA"],
    ["nome" => "Kevin Mac Allister", "posicao" => "LD"],

    // ==================== ESCÓCIA ====================

    ["nome" => "Kasper Schmeichel", "posicao" => "GOL"],
    ["nome" => "Cameron Carter-Vickers", "posicao" => "ZAG"],
    ["nome" => "Auston Trusty", "posicao" => "ZAG"],
    ["nome" => "Alistair Johnston", "posicao" => "LD"],
    ["nome" => "Kieran Tierney", "posicao" => "LE"],
    ["nome" => "Callum McGregor", "posicao" => "MC"],
    ["nome" => "Arne Engels", "posicao" => "MC"],
    ["nome" => "Reo Hatate", "posicao" => "MEI"],
    ["nome" => "Benjamin Nygren", "posicao" => "MEI"],
    ["nome" => "Nicolas Kühn", "posicao" => "PD"],
    ["nome" => "Luis Palma", "posicao" => "PD"],
    ["nome" => "Yang Hyun-jun", "posicao" => "PD"],
    ["nome" => "Daizen Maeda", "posicao" => "PE"],
    ["nome" => "Kyogo Furuhashi", "posicao" => "ATA"],
    ["nome" => "James Tavernier", "posicao" => "LD"],
    ["nome" => "Jefté", "posicao" => "ZAG"],
    ["nome" => "Nico Raskin", "posicao" => "MC"],
    ["nome" => "Mohamed Diomande", "posicao" => "MC"],
    ["nome" => "Hamza Igamane", "posicao" => "ATA"],

    // ==================== TURQUIA E GRÉCIA ====================

    // Galatasaray
    ["nome" => "Davinson Sánchez", "posicao" => "ZAG"],
    ["nome" => "Abdülkerim Bardakcı", "posicao" => "ZAG"],
    ["nome" => "Wilfried Singo", "posicao" => "LD"],
    ["nome" => "Ismail Jakobs", "posicao" => "LE"],
    ["nome" => "Lucas Torreira", "posicao" => "VOL"],
    ["nome" => "Mario Lemina", "posicao" => "VOL"],
    ["nome" => "İlkay Gündoğan", "posicao" => "MC"],
    ["nome" => "Gabriel Sara", "posicao" => "MC"],
    ["nome" => "Leroy Sané", "posicao" => "PD"],
    ["nome" => "Barış Alper Yılmaz", "posicao" => "PD"],
    ["nome" => "Yunus Akgün", "posicao" => "PD"],
    ["nome" => "Victor Osimhen", "posicao" => "ATA"],
    ["nome" => "Mauro Icardi", "posicao" => "ATA"],

    // Fenerbahçe
    ["nome" => "Ederson", "posicao" => "GOL"],
    ["nome" => "Dominik Livaković", "posicao" => "GOL"],
    ["nome" => "Milan Škriniar", "posicao" => "ZAG"],
    ["nome" => "Çağlar Söyüncü", "posicao" => "ZAG"],
    ["nome" => "Nélson Semedo", "posicao" => "LD"],
    ["nome" => "Filip Kostić", "posicao" => "LE"],
    ["nome" => "N'Golo Kanté", "posicao" => "VOL"],
    ["nome" => "İsmail Yüksek", "posicao" => "VOL"],
    ["nome" => "Fred", "posicao" => "MC"],
    ["nome" => "Sebastian Szymański", "posicao" => "MEI"],
    ["nome" => "Anderson Talisca", "posicao" => "MEI"],
    ["nome" => "Marco Asensio", "posicao" => "MEI"],
    ["nome" => "İrfan Can Kahveci", "posicao" => "MEI"],
    ["nome" => "Youssef En-Nesyri", "posicao" => "ATA"],
    ["nome" => "Jhon Durán", "posicao" => "ATA"],

    // Beşiktaş e Trabzonspor
    ["nome" => "Mert Günok", "posicao" => "GOL"],
    ["nome" => "Felix Uduokhai", "posicao" => "ZAG"],
    ["nome" => "Wilfred Ndidi", "posicao" => "VOL"],
    ["nome" => "Orkun Kökçü", "posicao" => "MC"],
    ["nome" => "Gedson Fernandes", "posicao" => "MC"],
    ["nome" => "Rafa Silva", "posicao" => "MEI"],
    ["nome" => "Milot Rashica", "posicao" => "PD"],
    ["nome" => "Semih Kılıçsoy", "posicao" => "ATA"],
    ["nome" => "Tammy Abraham", "posicao" => "ATA"],
    ["nome" => "Uğurcan Çakır", "posicao" => "GOL"],
    ["nome" => "Paul Onuachu", "posicao" => "ATA"],

    // Grécia e leste europeu
    ["nome" => "Ayoub El Kaabi", "posicao" => "ATA"],
    ["nome" => "Mehdi Taremi", "posicao" => "ATA"],
    ["nome" => "Chiquinho", "posicao" => "PE"],
    ["nome" => "Gelson Martins", "posicao" => "PD"],
    ["nome" => "Daniel Podence", "posicao" => "PE"],
    ["nome" => "Santiago Hezze", "posicao" => "MC"],
    ["nome" => "Giannis Konstantelias", "posicao" => "MEI"],
    ["nome" => "Andrija Živković", "posicao" => "PD"],
    ["nome" => "Filip Đuričić", "posicao" => "MEI"],
    ["nome" => "Facundo Pellistri", "posicao" => "PD"],
    ["nome" => "Marko Arnautović", "posicao" => "ATA"],
    ["nome" => "Mirko Ivanić", "posicao" => "MEI"],
    ["nome" => "Ismaël Bennacer", "posicao" => "MC"],
    ["nome" => "Maurits Kjærgaard", "posicao" => "MEI"],
    ["nome" => "Petar Ratkov", "posicao" => "ATA"],
    ["nome" => "Kasper Høgh", "posicao" => "ATA"],
    ["nome" => "Jens Petter Hauge", "posicao" => "PE"],
    ["nome" => "Hugo Vetlesen", "posicao" => "MEI"],

    // ==================== ARÁBIA SAUDITA ====================

    // Al-Nassr
    ["nome" => "Cristiano Ronaldo", "posicao" => "ATA"],
    ["nome" => "João Félix", "posicao" => "MEI"],
    ["nome" => "Sadio Mané", "posicao" => "PE"],
    ["nome" => "Kingsley Coman", "posicao" => "PE"],
    ["nome" => "Marcelo Brozović", "posicao" => "VOL"],
    ["nome" => "Iñigo Martínez", "posicao" => "ZAG"],
    ["nome" => "Mohamed Simakan", "posicao" => "ZAG"],
    ["nome" => "Alex Telles", "posicao" => "LE"],
    ["nome" => "Bento", "posicao" => "GOL"],
    ["nome" => "Otávio", "posicao" => "MEI"],
    ["nome" => "Angelo Gabriel", "posicao" => "PE"],
    ["nome" => "Nawaf Boushal", "posicao" => "LD"],
    ["nome" => "Ayman Yahya", "posicao" => "PE"],
    ["nome" => "Sultan Al-Ghannam", "posicao" => "LD"],
    ["nome" => "Abdulelah Al-Amri", "posicao" => "ZAG"],

    // Al-Hilal
    ["nome" => "Yassine Bounou", "posicao" => "GOL"],
    ["nome" => "Kalidou Koulibaly", "posicao" => "ZAG"],
    ["nome" => "João Cancelo", "posicao" => "LD"],
    ["nome" => "Theo Hernández", "posicao" => "LE"],
    ["nome" => "Renan Lodi", "posicao" => "LE"],
    ["nome" => "Rúben Neves", "posicao" => "VOL"],
    ["nome" => "Sergej Milinković-Savić", "posicao" => "MC"],
    ["nome" => "Mohamed Kanno", "posicao" => "MC"],
    ["nome" => "Malcom", "posicao" => "PD"],
    ["nome" => "Salem Al-Dawsari", "posicao" => "PE"],
    ["nome" => "Darwin Núñez", "posicao" => "ATA"],
    ["nome" => "Marcos Leonardo", "posicao" => "ATA"],
    ["nome" => "Aleksandar Mitrović", "posicao" => "ATA"],

    // Al-Ahli
    ["nome" => "Édouard Mendy", "posicao" => "GOL"],
    ["nome" => "Merih Demiral", "posicao" => "ZAG"],
    ["nome" => "Roger Ibañez", "posicao" => "ZAG"],
    ["nome" => "Ali Majrashi", "posicao" => "LD"],
    ["nome" => "Franck Kessié", "posicao" => "MC"],
    ["nome" => "Enzo Millot", "posicao" => "MEI"],
    ["nome" => "Riyad Mahrez", "posicao" => "PD"],
    ["nome" => "Galeno", "posicao" => "PE"],
    ["nome" => "Roberto Firmino", "posicao" => "ATA"],
    ["nome" => "Ivan Toney", "posicao" => "ATA"],

    // Al-Ittihad, Al-Qadsiah e outros
    ["nome" => "Marcelo Grohe", "posicao" => "GOL"],
    ["nome" => "Danilo Pereira", "posicao" => "ZAG"],
    ["nome" => "Mario Mitaj", "posicao" => "LE"],
    ["nome" => "Fabinho", "posicao" => "VOL"],
    ["nome" => "Houssem Aouar", "posicao" => "MC"],
    ["nome" => "Moussa Diaby", "posicao" => "PD"],
    ["nome" => "Steven Bergwijn", "posicao" => "PE"],
    ["nome" => "Karim Benzema", "posicao" => "ATA"],
    ["nome" => "Nahitan Nández", "posicao" => "MC"],
    ["nome" => "Julián Quiñones", "posicao" => "PE"],
    ["nome" => "Mateo Retegui", "posicao" => "ATA"],
    ["nome" => "Pierre-Emerick Aubameyang", "posicao" => "ATA"],
    ["nome" => "Georginio Wijnaldum", "posicao" => "MC"],
    ["nome" => "Yannick Carrasco", "posicao" => "PE"],
    ["nome" => "Demarai Gray", "posicao" => "PE"],
    ["nome" => "Moussa Dembélé", "posicao" => "ATA"],

    // ==================== MLS E LIGA MX ====================

    ["nome" => "Lionel Messi", "posicao" => "PD"],
    ["nome" => "Luis Suárez", "posicao" => "ATA"],
    ["nome" => "Sergio Busquets", "posicao" => "VOL"],
    ["nome" => "Jordi Alba", "posicao" => "LE"],
    ["nome" => "Tadeo Allende", "posicao" => "ATA"],
    ["nome" => "Telasco Segovia", "posicao" => "MEI"],
    ["nome" => "Son Heung-min", "posicao" => "PE"],
    ["nome" => "Hugo Lloris", "posicao" => "GOL"],
    ["nome" => "Denis Bouanga", "posicao" => "PE"],
    ["nome" => "David Martínez", "posicao" => "PD"],
    ["nome" => "Riqui Puig", "posicao" => "MC"],
    ["nome" => "Marco Reus", "posicao" => "MEI"],
    ["nome" => "Joseph Paintsil", "posicao" => "PD"],
    ["nome" => "Gabriel Pec", "posicao" => "PE"],
    ["nome" => "Thomas Müller", "posicao" => "MEI"],
    ["nome" => "Timo Werner", "posicao" => "ATA"],
    ["nome" => "Hany Mukhtar", "posicao" => "MEI"],
    ["nome" => "Evander", "posicao" => "MEI"],
    ["nome" => "Sam Surridge", "posicao" => "ATA"],
    ["nome" => "Miguel Almirón", "posicao" => "PD"],
    ["nome" => "Diego Luna", "posicao" => "MEI"],
    ["nome" => "Sebastián Driussi", "posicao" => "MEI"],
    ["nome" => "Petar Musa", "posicao" => "ATA"],
    ["nome" => "Jesús Ferreira", "posicao" => "ATA"],
    ["nome" => "Emmanuel Latte Lath", "posicao" => "ATA"],
    ["nome" => "Hirving Lozano", "posicao" => "PE"],
    ["nome" => "Matt Freese", "posicao" => "GOL"],
    ["nome" => "Matt Turner", "posicao" => "GOL"],
    ["nome" => "Sebastian Berhalter", "posicao" => "MC"],
    ["nome" => "Patrick Agyemang", "posicao" => "ATA"],
    ["nome" => "Christian Benteke", "posicao" => "ATA"],
    ["nome" => "Tim Ream", "posicao" => "ZAG"],
    ["nome" => "Gio Reyna", "posicao" => "MEI"],
    ["nome" => "Sergio Ramos", "posicao" => "ZAG"],
    ["nome" => "James Rodríguez", "posicao" => "MEI"],
    ["nome" => "André-Pierre Gignac", "posicao" => "ATA"],
    ["nome" => "Henry Martín", "posicao" => "ATA"],
    ["nome" => "Álvaro Fidalgo", "posicao" => "MEI"],
    ["nome" => "Brian Rodríguez", "posicao" => "PD"],
    ["nome" => "Ángel Correa", "posicao" => "ATA"],
    ["nome" => "Alexis Vega", "posicao" => "PE"],
    ["nome" => "Marcelo Flores", "posicao" => "MEI"],
    ["nome" => "Keylor Navas", "posicao" => "GOL"],
    ["nome" => "Guillermo Ochoa", "posicao" => "GOL"],
    ["nome" => "Orbelín Pineda", "posicao" => "MEI"],

    // ==================== ARGENTINA ====================

    ["nome" => "Leandro Paredes", "posicao" => "MC"],
    ["nome" => "Miguel Merentiel", "posicao" => "ATA"],
    ["nome" => "Edinson Cavani", "posicao" => "ATA"],
    ["nome" => "Exequiel Zeballos", "posicao" => "PE"],
    ["nome" => "Ander Herrera", "posicao" => "MC"],
    ["nome" => "Marcos Rojo", "posicao" => "ZAG"],
    ["nome" => "Kevin Zenón", "posicao" => "MEI"],
    ["nome" => "Carlos Palacios", "posicao" => "MEI"],
    ["nome" => "Franco Armani", "posicao" => "GOL"],
    ["nome" => "Facundo Colidio", "posicao" => "PE"],
    ["nome" => "Maximiliano Salas", "posicao" => "ATA"],
    ["nome" => "Nacho Fernández", "posicao" => "MEI"],
    ["nome" => "Kendry Páez", "posicao" => "MEI"],
    ["nome" => "Lucas Martínez Quarta", "posicao" => "ZAG"],
    ["nome" => "Gonzalo Montiel", "posicao" => "LD"],
    ["nome" => "Sebastián Boselli", "posicao" => "VOL"],
    ["nome" => "Juanfer Quintero", "posicao" => "MEI"],
    ["nome" => "Miguel Borja", "posicao" => "ATA"],
    ["nome" => "Ángel Di María", "posicao" => "PD"],
    ["nome" => "Adrián Martínez", "posicao" => "ATA"],
    ["nome" => "Gabriel Arias", "posicao" => "GOL"],

    // ==================== SELEÇÕES: OUTROS NOMES RELEVANTES ====================

    ["nome" => "Takehiro Tomiyasu", "posicao" => "LD"],
    ["nome" => "Mehdi Benatia", "posicao" => "ZAG"],
    ["nome" => "Jesper Cajuste", "posicao" => "MC"],
    ["nome" => "Anthony Martial", "posicao" => "ATA"]
];
